Packer base
Otus-DevOps-2023-03/Zikaf_infra pull request #4
Opened 2023-06-07 13:31 UTC by Zikaf

# Выполнено ДЗ №7
 -  Основное ДЗ
 -  Все задания со *

## В процессе сделано:
 - Скрипты, артефакт, создание вирт. машины + сервис
 - Автоматизация установки

## Как запустить проект:
 - Он запущен, информация в Readme

## Как проверить работоспособность:
 - http:/51.250.14.208:9292/

## PR checklist
 - [ ] Выставил label с темой домашнего задания

2023-06-07 19:37 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Рекомендую свериться с результатами тестов
Вам нужно добавить в репозиторий фейковый ключик и прописать для него путь
Приключение на 10 минут
ДЗ возвращаю на доработку

2023-06-07 20:07 UTC, Zikaf commented
Я уже пробовал добавлять фейковый ключ и указывать его местоположение
его можно увидеть по пути
https://github.com/Otus-DevOps-2023-03/Zikaf_infra/pull/4/files

2023-06-13 14:43 UTC, mrgreyves requested changes
Здравствуйте!
На раннере вот тут /otus/4_github-project/Zikaf_infra/packer/key.json
точно нет вашего ключа
Посмотрите в какой директории запускается пакер, положите туда ключ и укажите этот файл в конфиге

2023-06-17 12:29 UTC, Zikaf commented
Если ранее обращали внимание, у меня много "test" коммитов
куда я только не клал key.json

Ошибка 
expected: "Template validated successfully.\n"
          got: "Template validation failed. Errors are shown below.\n\nErrors validating build 'yandex'. 1 error(s) ...on' read fail: open /otus/4_github-project/Zikaf_infra/packer/key.json: no such file or directory\n"
          
          сразу была мне понятна, но почему он не видит этого файла, я не понимаю
          я и права менял и пути

2023-06-25 13:18 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2023-06-26 06:33 UTC, merged